FROM maven:3.9-eclipse-temurin-25 AS build

WORKDIR /app

COPY backend-java/pom.xml .
COPY backend-java/src ./src

RUN mvn -q -DskipTests package

FROM eclipse-temurin:25-jre

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8086

ENTRYPOINT ["java", "-jar", "app.jar"]
