server:
  port: ${PORT:8086}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/hrs_tech}
    username: ${SPRING_DATASOURCE_USERNAME:hrs}
    password: ${SPRING_DATASOURCE_PASSWORD:hrs}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health
